config/routes.rb
RoR::Application.routes.draw do
 resources :cats do
	resources :rates
end

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/cats.rb
class Cats < ActiveRecord::Base
	has_many :rates, dependent: :destroy
	validates :category, presence: true,
                    length: { minimum: 3 }

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
	 http_basic_authenticate_with name: "dhh", password: "secret", 
	 except: [:index, :show]
 


	def new
		@cat=Cats.new
    end

	def edit
 		 @cat = Cats.find(params[:id])
	end

	def create
 	 @cat= Cats.new(cat_params)
 
 	 	if @cat.save
 	 		redirect_to @cat
 	 	else
 	 		render 'new'
		end
	end

	def update
  		@article = Article.find(params[:id])
 
  		if @article.update(article_params)
    		redirect_to @article
  		else
    		render 'edit'
  		end
	end

	def destroy
   		@cat = Cats.find(params[:id])
    	@cat.destroy
 
   		redirect_to cats_path
	end

	public
	def cat_params
		params.require(:cat).permit(:category, :title)
	end

	def show
		@cats = Cats.find(params[:id])
	end

	def index
		@cats = Cats.all 
	end

end

app/controllers/rate_controller.rb
class RateController < ApplicationController
	http_basic_authenticate_with name: "dhh", password: "secret", 
	only: :destroy

	def create
    	@cat = Cats.find(params[:cat_id])
    	@rate = @cat.rate.create(rate_params)
    	redirect_to cat_path(@cat)
  	end

  	def destroy
    	@cat = Cats.find(params[:cat_id])
    	@cat = @cat.rates.find(params[:id])
    	@rate.destroy
    	redirect_to cat_path(@cat)
	end
 
  public
    def rate_params
      params.require(:rate).permit(:body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/rate_helper.rb
module RateHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cats/edit.html.erb
<h1>Editing category</h1>
 
<%= form_for :cat, url: cats_path(@cat), method: :patch do |f| %>
 
  <% if @cat.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@cat.errors.count, "error") %> prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @cat.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 

app/views/cats/index.html.erb
<h1> categories</h1>
 
<table>
  <tr>
    <th>category</th>
    <th>title</th>
	<th colspan="3"></th>
  </tr>
 
  <% @cats.each do |cat| %>
    <tr>
      <td><%= cat.category %></td>
      <td><%= cat.title %></td>
	  <td><%= link_to 'Show', cats_path(cat) %></td>
      <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
   
 <td><%= link_to 'Destroy', cat_path(cat),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
  <% end %>
</table>

app/views/cats/new.html.erb
<%= form_for :cat, url: cats_path do |f| %>
  
  <% if @cat.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@cat.errors.count, "error") %> prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @cat.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/cats/show.html.erb
<p>
  <strong>category:</strong>
  <%= @cats.category %>
</p>
 
<p>
  <strong>title:</strong>
  <%= @cats.title %>
</p>

 
<h2>rates</h2>
<% @cats.rate.each do |rate| %>
 
  <p>
    <strong>rate:</strong>
    <%= rate.body %>
  </p>
<% end %>

<h2>Add a rate:</h2>
<%= form_for([@cat, @cat.rate.build]) do |f| %>
 
  <p>
    <%= f.label :body %><br>
    <%= f.integer :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoR</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rate/_form.html.erb
<%= form_for([@cat, @cat.rates.build]) do |f| %>
 
  <p>
    <%= f.label :body %><br>
    <%= f.integer :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/rate/_rate.html.erb
 
<p>
  <strong>rate:</strong>
  <%= rate.body %>
</p>
 
<p>
  <%= link_to 'Destroy Rate', [rate.cat, rate],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>